/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medicamentos.Accesorios;

import Datos.Alimento;
import Datos.ArrayNuevos;
import Datos.CarritodeCompras;
import Datos.ToysDat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import proyectofinal.VprincipalMedicamenros;

/**
 *
 * @author LuisM
 */
public class Food extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    public Food() {
        this.setUndecorated(true);
        initComponents();
        foodtab.setModel(modelo);
        modelo.addColumn("Marca");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        cargardatos();
    }
        public void cargardatos(){
        if (ArrayNuevos.NuevoAlimento.size()== 0){
        Alimento a1 = new Alimento();
        a1.setNombre("Kan 10 kilos"); 
        a1.setValor("Alimento para perro");
        a1.setPrecio(8000);
        
        Alimento a2 = new Alimento();
        a2.setNombre("Kan 5 kilos");
        a2.setValor("Alimento para perro");
        a2.setPrecio(6000);
        
        Alimento a3 = new Alimento();
        a3.setNombre("Kan 30 kilos");
        a3.setValor("Alimento para perro");
        a3.setPrecio(36000);
        
        Alimento a4 = new Alimento();
        a4.setNombre("Milen 3 k");
        a4.setValor("Alimento para perro");
        a4.setPrecio(3000);
        
        Alimento a5 = new Alimento();
        a5.setNombre("Milen 10 kilos");
        a5.setValor("Alimento para perro");
        a5.setPrecio(16000);
        
        ArrayNuevos.NuevoAlimento.add(a1);
        ArrayNuevos.NuevoAlimento.add(a2);
        ArrayNuevos.NuevoAlimento.add(a3);
        ArrayNuevos.NuevoAlimento.add(a4);
        ArrayNuevos.NuevoAlimento.add(a5);
        }
        modelo.setRowCount(0);
        
        for (int i = 0; i < ArrayNuevos.NuevoAlimento.size(); i++) {

           modelo.addRow(new Object[]{
           ArrayNuevos.NuevoAlimento.get(i).getNombre(),
           ArrayNuevos.NuevoAlimento.get(i).getValor(),
           ArrayNuevos.NuevoAlimento.get(i).getPrecio()
                 
        }); 
        }
           
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        foodtab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(207, 61, 142));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(55, 43, 172));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Descripcion", "Precio",
            }
        ));
        jScrollPane1.setViewportView(foodtab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 370, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel1.setText("Volver");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BTN Volcer.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 13)); // NOI18N
        jLabel5.setText("Agregar Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 120, -1));

        btnCarrito.setText("Agregar");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Geometry_Texture_Blue_Light_Blue_White_background_586221_1280x791.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(580, 360));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));
        jLabel2.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        VprincipalMedicamenros vpmed = new VprincipalMedicamenros();
        vpmed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        
        int indice = foodtab.getSelectedRow();
        
        
        String nombre = ArrayNuevos.NuevoAlimento.get(indice).getNombre();
        String valor = ArrayNuevos.NuevoAlimento.get(indice).getValor();
        int precio = ArrayNuevos.NuevoAlimento.get(indice).getPrecio();
        
        SpinnerNumberModel sModel = new SpinnerNumberModel(1, 0, 30, 1);
        JSpinner spinner = new JSpinner(sModel);
        int option = JOptionPane.showOptionDialog(null, spinner, "Seleccione las unidades que desea agregar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (option == JOptionPane.CANCEL_OPTION){
            System.out.println("El cliente canceló la operación");
        } 
        else if (option == JOptionPane.OK_OPTION){
            int cantidad = (Integer)spinner.getValue();
            int total = precio*cantidad;

            CarritodeCompras producto = new CarritodeCompras();
            //Instanciar objeto
            producto.setNombre(nombre);
            producto.setValor(valor);
            producto.setPrecio(total);
            producto.setCantidad(cantidad);
            ArrayNuevos.nuevosCarritodeCompras.add(producto);
            JOptionPane.showMessageDialog(null,"Su producto se agrego al carrito");
        }
    
        
    }//GEN-LAST:event_btnCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JTable foodtab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
