/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medicamentos.Accesorios;

import Datos.ArrayNuevos;
import Datos.CarritodeCompras;
import Datos.Limpieza;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import proyectofinal.VprincipalMedicamenros;

/**
 *
 * @author LuisM
 */
public class LimpVent extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    public LimpVent() {
        this.setUndecorated(true);
        initComponents();
        limtab.setModel(modelo);
        modelo.addColumn("Marca");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        cargardatos();
        
    }
        public void cargardatos(){
            if (ArrayNuevos.NuevosLimpieza.size()== 0){
                Limpieza p1 = new Limpieza();
            p1.setNombre("Shampo Litro");
            p1.setValor("1.200");
            p1.setPrecio(1200);

            Limpieza p2 = new Limpieza();
            p2.setNombre("Shampo Medio");
            p2.setValor("2.600");
            p2.setPrecio(2600);

            Limpieza p3 = new Limpieza();
            p3.setNombre("Shampo Galon");
            p3.setValor("3.000");
            p3.setPrecio(3000);

            Limpieza p4 = new Limpieza();
            p4.setNombre("Esponja Pequena");
            p4.setValor("500");
            p4.setPrecio(500);

            Limpieza p5 = new Limpieza();
            p5.setNombre("Esponja Grande");
            p5.setValor("1.000");
            p5.setPrecio(1000);

            Limpieza p6 = new Limpieza();
            p6.setNombre("Jabon Ultix");
            p6.setValor("2.000");
            p6.setPrecio(2000);

            Limpieza p7 = new Limpieza();
            p7.setNombre("Jabon Multfirx");
            p7.setValor("2.000");
            p7.setPrecio(2000);
            
            ArrayNuevos.NuevosLimpieza.add(p1);
            ArrayNuevos.NuevosLimpieza.add(p2);
            ArrayNuevos.NuevosLimpieza.add(p3);
            ArrayNuevos.NuevosLimpieza.add(p4);
            ArrayNuevos.NuevosLimpieza.add(p5);
            ArrayNuevos.NuevosLimpieza.add(p6);
            ArrayNuevos.NuevosLimpieza.add(p7);            
        }
            modelo.setRowCount(0);
            
            for (int i = 0; i < ArrayNuevos.NuevosLimpieza.size(); i++) {

           modelo.addRow(new Object[]{
           ArrayNuevos.NuevosLimpieza.get(i).getNombre(),
           ArrayNuevos.NuevosLimpieza.get(i).getValor(),
           ArrayNuevos.NuevosLimpieza.get(i).getPrecio()
                 
        }); 
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        limtab = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        limtab.setAutoCreateRowSorter(true);
        limtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}

            },
            new String [] {
                "Producto", "Descripcion", "Precio"
            }
        ));
        jScrollPane1.setViewportView(limtab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 360, 288));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BTN Volcer.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel1.setText("Volver");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 13)); // NOI18N
        jLabel5.setText("Agregar Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 120, -1));

        btnCarrito.setText("Agregar");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Geometry_Texture_Blue_Light_Blue_White_background_586221_1280x791.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        VprincipalMedicamenros vpmed = new VprincipalMedicamenros();
        vpmed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
       
        int indice = limtab.getSelectedRow();
        String nombre = ArrayNuevos.NuevosLimpieza.get(indice).getNombre();
        String valor = ArrayNuevos.NuevosLimpieza.get(indice).getValor();
        int precio = ArrayNuevos.NuevosLimpieza.get(indice).getPrecio();
        
        SpinnerNumberModel sModel = new SpinnerNumberModel(1, 0, 30, 1);
        JSpinner spinner = new JSpinner(sModel);
        int option = JOptionPane.showOptionDialog(null, spinner, "Seleccione las unidades que desea agregar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (option == JOptionPane.CANCEL_OPTION){
            System.out.println("El cliente canceló la operación");
        } 
        else if (option == JOptionPane.OK_OPTION){
            int cantidad = (Integer)spinner.getValue();
            int total = precio*cantidad;

            CarritodeCompras producto = new CarritodeCompras();
            //Instanciar objeto
            producto.setNombre(nombre);
            producto.setValor(valor);
            producto.setPrecio(total);
            producto.setCantidad(cantidad);
            ArrayNuevos.nuevosCarritodeCompras.add(producto);
            JOptionPane.showMessageDialog(null,"Su producto se agrego al carrito");
        }
    }//GEN-LAST:event_btnCarritoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LimpVent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LimpVent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LimpVent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LimpVent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LimpVent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable limtab;
    // End of variables declaration//GEN-END:variables
}
