/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medicamentos.Accesorios;

import Datos.ArrayNuevos;
import Datos.CarritodeCompras;
import Datos.MediRece;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import proyectofinal.VprincipalMedicamenros;

/**
 *
 * @author LuisM
 */
public class MedRece extends javax.swing.JFrame {

    /**
     * Creates new form MedRece
     */
    DefaultTableModel tablaMR = new DefaultTableModel();
    public MedRece() {
        this.setUndecorated(true);
        initComponents();
        tabMR.setModel(tablaMR);
        tablaMR.addColumn("Marca");
        tablaMR.addColumn("Descripcion");
        tablaMR.addColumn("Precio");
        cargarDatos();
        
    }
    public void cargarDatos(){
        if (ArrayNuevos.NuevosMediRece.size() == 0) {
            
        
        MediRece MR1 = new MediRece();
        MR1.setNombre("Rimadyl");
        MR1.setDescripcion("Pomada");
        MR1.setPrecio(800);
        MediRece MR2 = new MediRece();
        MR2.setNombre("Deramaxx");
        MR2.setDescripcion("Pomada");
        MR2.setPrecio(1500);
        MediRece MR3 = new MediRece();
        MR3.setNombre("Etogesic");
        MR3.setDescripcion("Pomada");
        MR3.setPrecio(2000);
        MediRece MR4 = new MediRece();
        MR4.setNombre("Metacam");
        MR4.setDescripcion("Pastilla");
        MR4.setPrecio(5000);
        MediRece MR5 = new MediRece();
        MR5.setNombre("Metamol");
        MR4.setDescripcion("Pastilla");
        MR4.setPrecio(6000);
        ArrayNuevos.NuevosMediRece.add(MR1);
        ArrayNuevos.NuevosMediRece.add(MR2);
        ArrayNuevos.NuevosMediRece.add(MR3);
        ArrayNuevos.NuevosMediRece.add(MR4);
        ArrayNuevos.NuevosMediRece.add(MR5);
        }
        tablaMR.setRowCount(0);
        
        
        for (int i = 0; i < ArrayNuevos.NuevosMediRece.size(); i++) {

           tablaMR.addRow(new Object[]{
           ArrayNuevos.NuevosMediRece.get(i).getNombre(),
           ArrayNuevos.NuevosMediRece.get(i).getDescripcion(),
           ArrayNuevos.NuevosMediRece.get(i).getPrecio()
                 
        }); 
        }
        
        
       
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMR = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Medicamentos Recetados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        tabMR.setAutoCreateRowSorter(true);
        tabMR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Detalle", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tabMR);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 370, 300));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BTN Volcer.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 70, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel2.setText("Volver");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 13)); // NOI18N
        jLabel5.setText("Agregar Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 120, -1));

        btnCarrito.setText("Agregar");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Geometry_Texture_Blue_Light_Blue_White_background_586221_1280x791.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 580, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        VprincipalMedicamenros vpmed = new VprincipalMedicamenros();
        vpmed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        
        int indice = tabMR.getSelectedRow();
        String nombre = ArrayNuevos.NuevosMediRece.get(indice).getNombre();
        String descripcion = ArrayNuevos.NuevosMediRece.get(indice).getDescripcion();
        int precio = ArrayNuevos.NuevosMediRece.get(indice).getPrecio();
        
        SpinnerNumberModel sModel = new SpinnerNumberModel(1, 0, 30, 1);
        JSpinner spinner = new JSpinner(sModel);
        int option = JOptionPane.showOptionDialog(null, spinner, "Seleccione las unidades que desea agregar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (option == JOptionPane.CANCEL_OPTION){
            System.out.println("El cliente canceló la operación");
        } 
        else if (option == JOptionPane.OK_OPTION){
            int cantidad = (Integer)spinner.getValue();
            int total = precio*cantidad;

            CarritodeCompras producto = new CarritodeCompras();
            //Instanciar objeto
            producto.setNombre(nombre);
            producto.setValor(descripcion);
            producto.setPrecio(total);
            producto.setCantidad(cantidad);
            ArrayNuevos.nuevosCarritodeCompras.add(producto);
            JOptionPane.showMessageDialog(null,"Su producto se agrego al carrito");
        }
    }//GEN-LAST:event_btnCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedRece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedRece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedRece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedRece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedRece().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabMR;
    // End of variables declaration//GEN-END:variables
}
