/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medicamentos.Accesorios;

import Datos.ArrayNuevos;
import Datos.CarritodeCompras;
import Datos.ToysDat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import proyectofinal.VPrincipal;
import proyectofinal.VprincipalMedicamenros;

/**
 *
 * @author LuisM
 */
public class Toys extends javax.swing.JFrame {

    /**
     * Creates new form Toys
     */
    DefaultTableModel tablaToys = new DefaultTableModel();
    public Toys() {
        this.setUndecorated(true);
        initComponents();
        toytab.setModel(tablaToys);
        tablaToys.addColumn("Marca");
        tablaToys.addColumn("Descripción");
        tablaToys.addColumn("Precio");
        cagarDatos();
    }
    public void cagarDatos(){
        if (ArrayNuevos.NuevosToys.size() == 0) {
            
        
        ToysDat p1 = new ToysDat();
        p1.setNombre("Raton de peluche");
        p1.setValor("850");
        p1.setPrecio(850);
        
        ToysDat p2 = new ToysDat();
        p2.setNombre("Mordedor de hueso");
        p2.setValor("1.500");
        p2.setPrecio(1500);
        
        ToysDat p3 = new ToysDat();
        p3.setNombre("Bolita masticable");
        p3.setValor("1.000");
        p3.setPrecio(1000);
        
        ToysDat p4 = new ToysDat();
        p4.setNombre("Bolita hule");
        p4.setValor("1.500");
        p4.setPrecio(1500);
        
        ToysDat p5 = new ToysDat();
        p5.setNombre("Hueso Peluche");
        p5.setValor("2.500");
        p5.setPrecio(2500);
        
        ArrayNuevos.NuevosToys.add(p1);
        ArrayNuevos.NuevosToys.add(p2);
        ArrayNuevos.NuevosToys.add(p3);
        ArrayNuevos.NuevosToys.add(p4);
        ArrayNuevos.NuevosToys.add(p5);
        }
        tablaToys.setRowCount(0);
        
        
        for (int i = 0; i < ArrayNuevos.NuevosToys.size(); i++) {

           tablaToys.addRow(new Object[]{
           ArrayNuevos.NuevosToys.get(i).getNombre(),
           ArrayNuevos.NuevosToys.get(i).getValor(),
           ArrayNuevos.NuevosToys.get(i).getPrecio()
                 
        }); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        toytab = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Juguetes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 16, -1, -1));

        toytab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Descripcion", "Precio",
            }
        ));
        jScrollPane1.setViewportView(toytab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 38, 380, 310));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BTN Volcer.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 70, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel2.setText("Volver");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 13)); // NOI18N
        jLabel5.setText("Agregar Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 120, -1));

        btnCarrito.setText("Agregar");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Geometry_Texture_Blue_Light_Blue_White_background_586221_1280x791.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        VprincipalMedicamenros vpmed = new VprincipalMedicamenros();
        vpmed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        
        int indice = toytab.getSelectedRow();
        String nombre = ArrayNuevos.NuevosToys.get(indice).getNombre();
        String valor = ArrayNuevos.NuevosToys.get(indice).getValor();
        int precio = ArrayNuevos.NuevosToys.get(indice).getPrecio();
        
        SpinnerNumberModel sModel = new SpinnerNumberModel(1, 0, 30, 1);
        JSpinner spinner = new JSpinner(sModel);
        int option = JOptionPane.showOptionDialog(null, spinner, "Seleccione las unidades que desea agregar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (option == JOptionPane.CANCEL_OPTION){
            System.out.println("El cliente canceló la operación");
        } 
        else if (option == JOptionPane.OK_OPTION){
            int cantidad = (Integer)spinner.getValue();
            int total = precio*cantidad;

            CarritodeCompras producto = new CarritodeCompras();
            //Instanciar objeto
            producto.setNombre(nombre);
            producto.setValor(valor);
            producto.setPrecio(total);
            producto.setCantidad(cantidad);
            ArrayNuevos.nuevosCarritodeCompras.add(producto);
            JOptionPane.showMessageDialog(null,"Su producto se agrego al carrito");
            
        }
    
    }//GEN-LAST:event_btnCarritoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable toytab;
    // End of variables declaration//GEN-END:variables
}
