
package proyectofinal;

import Datos.ArrayNuevos;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LuisM
 */
public class VCCompras extends javax.swing.JFrame {
    
    
    double precio=0;
    int cantidad=0;
    
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form VCCompras
     */
    public VCCompras() {
        initComponents();
        tablaCarrito.setModel(modelo);
        modelo.addColumn("Marca");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        cargardatos();
        
     }
    
    public void cargardatos(){
        modelo.setRowCount(0);
        
        int Subtot = 0;
        
        
        for (int i = 0; i < ArrayNuevos.nuevosCarritodeCompras.size(); i++) {

           modelo.addRow(new Object[]{
           ArrayNuevos.nuevosCarritodeCompras.get(i).getNombre(),
           ArrayNuevos.nuevosCarritodeCompras.get(i).getValor(),
           ArrayNuevos.nuevosCarritodeCompras.get(i).getPrecio(),
           ArrayNuevos.nuevosCarritodeCompras.get(i).getCantidad()
                   
           });
           
           Subtot = Subtot + ArrayNuevos.nuevosCarritodeCompras.get(i).getPrecio();
        }
        
        TxtSubtotal.setText(Integer.toString(Subtot));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TxtSubtotal = new javax.swing.JTextField();
        comboMetodo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BtnAtras = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnDescuento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Descrpcion", "Precio","Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaCarrito);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 400, 307));

        jLabel1.setText("Total");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 29, -1, -1));
        getContentPane().add(TxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 51, 72, -1));

        comboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta"}));
        comboMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMetodoActionPerformed(evt);
            }
        });
        getContentPane().add(comboMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 119, -1, -1));

        jLabel2.setText("Metodo de pago");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 91, -1, -1));

        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BTN Volcer.png"))); // NOI18N
        BtnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtrasMouseClicked(evt);
            }
        });
        BtnAtras.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                BtnAtrasCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        getContentPane().add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 70, 40));

        jLabel3.setText("Total Final");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 239, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 273, 72, -1));

        btnDescuento.setText("Aplicar descuneto");
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 159, -1, -1));

        jLabel4.setText("*Solo se aplica si es ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 187, -1, -1));

        jLabel5.setText("pago en efectivo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 205, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel8.setText("Volver");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btndelete.setText("Eliminar producto");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/empty-shopping-cart-on-wooden-table-with-blue-background-free-photo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_BtnAtrasCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAtrasCaretPositionChanged

    private void BtnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtrasMouseClicked
        VprincipalMedicamenros vpmed = new VprincipalMedicamenros();
        vpmed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasMouseClicked

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        int Subtot;
        
        
        Subtot = Integer.parseInt(TxtSubtotal.getText());
        double dcto;
        if(comboMetodo.getSelectedItem().equals("<Seleccionar>")){
           JOptionPane.showMessageDialog(null,"Seleccione una forma de pago");
           return;
        }else{
        }
          
        if(comboMetodo.getSelectedItem().equals("Efectivo")){
            dcto = Subtot * 0.95;
            txtTotal.setText(Integer.toString((int)dcto));
            
        }else if (comboMetodo.getSelectedItem().equals("Tarjeta")){ 
            txtTotal.setText(Integer.toString((int)Subtot));         
        }     
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void comboMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMetodoActionPerformed
        
    }//GEN-LAST:event_comboMetodoActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        if (tablaCarrito.getSelectedRow() != -1) {
            int index = tablaCarrito.getSelectedRow();
            int precioResta = ArrayNuevos.nuevosCarritodeCompras.get(index).getPrecio();
            int seteoPrecio = Integer.parseInt(TxtSubtotal.getText());
            int total =seteoPrecio - precioResta;
            TxtSubtotal.setText(String.valueOf(total));
            txtTotal.setText(String.valueOf(total));
            modelo.removeRow(index);
            ArrayNuevos.nuevosCarritodeCompras.remove(index);
                    
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un objeto de la tabla");
        }
        
        
        
    }//GEN-LAST:event_btndeleteActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new VCCompras().setVisible(true);
            }
        });   
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAtras;
    private javax.swing.JTextField TxtSubtotal;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btndelete;
    private javax.swing.JComboBox<String> comboMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    /*private void actualizarTabla() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /*private void calcularPrecio() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/
}
