/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaqueteAgendar;
 
import Datos.DatosCitas;
import Datos.IniciarDatos;
import Datos.Usuarios;
import PanelAdministrador.TablaDeCitas;
import PaqueteAgendar.PantallaDeFechas;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import proyectofinal.VPrincipal;

public class RegistroCitas extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public String valn;
    public String cita;
    public String sel;
    public RegistroCitas() {
        initComponents();
        
    }
    public void enviarComprobanteCita(){
        /*ClaseConeccionesCorreo e = new ClaseConeccionesCorreo();
        String Destino = txtCorreoelectronico.getText();
        String asunto = "Comprobante de cita";
        String cuerpo = "Nombre:"+txtNombre.getText()+"\n"+
                "Cedula: "+txtCed.getText()+"\n"+
                "Teléfono"+txtTel.getText()+"\n"+
                "Mascota: "+txtMascota.getText()+"\n"+
                "Fecha de la cita: "+txtFechaDeCita.getText();
    */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMascota = new javax.swing.JTextField();
        btnFecha = new javax.swing.JButton();
        txtFechaDeCita = new javax.swing.JTextField();
        btnAgendar = new javax.swing.JButton();
        txtCed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreoelectronico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPopupMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPopupMenu1MousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Registro de citas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 16));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 125, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 119, 179, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Cedula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tel:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 179, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Animal: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));
        getContentPane().add(txtMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 179, 50));

        btnFecha.setText("Consultar Fecha y horario");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 30));

        txtFechaDeCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaDeCitaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaDeCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 144, 30));

        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 342, 108, 30));
        getContentPane().add(txtCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 179, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BTN Volcer.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 40));
        getContentPane().add(txtCorreoelectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Correo electrónico");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flat-simple-wall-calendar-design-style-cartoon-illustration-drawing-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void jPopupMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu1MousePressed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        // TODO add your handling code here:
        PantallaDeFechas abrir = new PantallaDeFechas();
        abrir.setVisible(true);
        
        
    }//GEN-LAST:event_btnFechaActionPerformed

    private void txtFechaDeCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDeCitaActionPerformed
        // TODO add your handling code here:
        txtFechaDeCita.setText(cita);
    }//GEN-LAST:event_txtFechaDeCitaActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        VPrincipal vprin = new VPrincipal();
        vprin.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        String Nombre = txtNombre.getText();
        String tel = txtTel.getText();
        String ced = txtCed.getText();
        String correo = txtCorreoelectronico.getText();
        String animal = txtMascota.getText();
        String cita = txtFechaDeCita.getText();
        
        DatosCitas addDatos = new DatosCitas();
        addDatos.setNombre(Nombre);
        addDatos.setTel(tel);
        addDatos.setCed(ced);
        addDatos.setCorreo(correo);
        addDatos.setAnimales(animal);
        addDatos.setFechaCita(cita);
        ArrayStaticCitas.citaspendientes.add(addDatos);
        
        JOptionPane.showMessageDialog(rootPane, "Cita agendada");
        JOptionPane.showMessageDialog(rootPane, "Se ha enviado el comprobante a su correo porfavor revise su buzón");
        
        String Destino = txtCorreoelectronico.getText();
        //String asunto = "Comprobante de cita";
        /*String cuerpo = "Nombre:"+txtNombre.getText()+"\n"+
                "Cedula: "+txtCed.getText()+"\n"+
                "Teléfono"+txtTel.getText()+"\n"+
                "Mascota: "+txtMascota.getText()+"\n"+
                "Fecha de la cita: "+txtFechaDeCita.getText();*/
        ClaseConeccionesCorreo e = new ClaseConeccionesCorreo();
        try {
            e.envirConfimacionCorreo(Destino, "Comprobante de cita", "Nombre:"+txtNombre.getText()+"\t"+
                "Cedula: "+txtCed.getText()+"\t"+
                "Teléfono"+txtTel.getText()+"\t"+
                "Mascota: "+txtMascota.getText()+"\t"+
                "Fecha de la cita: "+txtFechaDeCita.getText());
            JOptionPane.showMessageDialog(rootPane, "Correo enviado");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(RegistroCitas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(RegistroCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNombre.setText(null);
        txtTel.setText(null);
        txtCorreoelectronico.setText(null);
        txtCed.setText(null);
        txtMascota.setText(null);
        txtFechaDeCita.setText(null);
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField txtCed;
    private javax.swing.JTextField txtCorreoelectronico;
    public static javax.swing.JTextField txtFechaDeCita;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

    void cita() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void cita(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
